//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ncepu.GraduationProject.Sis.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_BoilerIndex
    {
        public int Id { get; set; }
        public int UnitId { get; set; }
        public Nullable<decimal> MSPB { get; set; }
        public Nullable<decimal> MSTB { get; set; }
        public Nullable<decimal> RSPB { get; set; }
        public Nullable<decimal> RSTB { get; set; }
        public Nullable<decimal> DWF { get; set; }
        public Nullable<decimal> FWP { get; set; }
        public Nullable<decimal> FWF { get; set; }
        public Nullable<decimal> SEOC { get; set; }
        public Nullable<decimal> SEOT { get; set; }
        public Nullable<decimal> ACB { get; set; }
        public Nullable<decimal> BFW { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
