//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ncepu.GraduationProject.Sis.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SIS_BoilerIndex> SIS_BoilerIndex { get; set; }
        public DbSet<SIS_EnvrionmentalIndex> SIS_EnvrionmentalIndex { get; set; }
        public DbSet<SIS_MotorIndex> SIS_MotorIndex { get; set; }
        public DbSet<SIS_PlantSummary> SIS_PlantSummary { get; set; }
        public DbSet<SIS_PowerGeneration_Daily> SIS_PowerGeneration_Daily { get; set; }
        public DbSet<SIS_PowerGeneration_Hourly> SIS_PowerGeneration_Hourly { get; set; }
        public DbSet<SIS_PowerGeneration_Monthly> SIS_PowerGeneration_Monthly { get; set; }
        public DbSet<SIS_PowerGeneration_Yearly> SIS_PowerGeneration_Yearly { get; set; }
        public DbSet<SIS_TurbineIndex> SIS_TurbineIndex { get; set; }
        public DbSet<SIS_Unit> SIS_Unit { get; set; }
        public DbSet<SIS_TotalPowerGeneration_Daily> SIS_TotalPowerGeneration_Daily { get; set; }
        public DbSet<SIS_TotalPowerGeneration_Hourly> SIS_TotalPowerGeneration_Hourly { get; set; }
        public DbSet<SIS_TotalPowerGeneration_Monthly> SIS_TotalPowerGeneration_Monthly { get; set; }
        public DbSet<SIS_TotalPowerGeneration_Yearly> SIS_TotalPowerGeneration_Yearly { get; set; }
    }
}
